# Generated by Django 3.1.2 on 2020-11-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firstapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='기업이름')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('URL', models.CharField(max_length=200, verbose_name='URL')),
                ('desc', models.TextField(blank=True, verbose_name='본문')),
                ('pic', models.ImageField(blank=True, upload_to='', verbose_name='기업로고')),
                ('representative', models.CharField(max_length=200, verbose_name='대표자명')),
                ('telephone', models.CharField(max_length=200, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
            ],
        ),
    ]
