# Generated by Django 3.1.2 on 2020-11-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='business',
            field=models.CharField(default=11, max_length=200, verbose_name='분야'),
            preserve_default=False,
        ),
    ]
