# Generated by Django 3.1.2 on 2020-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_firstapp_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='advantage',
            field=models.CharField(default=123123, max_length=200, verbose_name='복리후생'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='volume',
            field=models.CharField(default=123123, max_length=200, verbose_name='모집인원'),
            preserve_default=False,
        ),
    ]
