# Generated by Django 3.1.2 on 2020-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20201110_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='career',
            field=models.CharField(default=123, max_length=200, verbose_name='경력'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='content',
            field=models.CharField(default=123, max_length=200, verbose_name='직무내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='diversification',
            field=models.CharField(default=123, max_length=200, verbose_name='고용형태'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='etc',
            field=models.CharField(default=123, max_length=500, verbose_name='기타사항'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='grade',
            field=models.CharField(default=123, max_length=200, verbose_name='학력'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='money',
            field=models.CharField(default=123, max_length=200, verbose_name='급여'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='time',
            field=models.CharField(default=123, max_length=200, verbose_name='근무시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='type',
            field=models.CharField(default=123, max_length=200, verbose_name='직종'),
            preserve_default=False,
        ),
    ]
