# Generated by Django 3.1.2 on 2020-11-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20201110_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstapp',
            name='desc',
        ),
        migrations.AlterField(
            model_name='firstapp',
            name='etc',
            field=models.TextField(max_length=500, verbose_name='기타사항'),
        ),
    ]
